import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import ExcelJS from "exceljs";

export interface ExportColumn {
  header: string;
  key: string;
  width?: number;
}

export interface ExportData {
  columns: ExportColumn[];
  rows: Record<string, string | number | boolean | null | undefined>[];
  title: string;
  subtitle?: string;
}

/**
 * Export data to PDF
 */
export async function exportToPDF(data: ExportData): Promise<void> {
  const doc = new jsPDF("landscape", "mm", "a4");

  // Header
  doc.setFontSize(18);
  doc.setTextColor(1, 66, 78); // #01424E
  doc.text("EventHub", 14, 15);

  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text(data.title, 14, 25);

  if (data.subtitle) {
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(data.subtitle, 14, 32);
  }

  // Table
  const headers = data.columns.map((col) => col.header);
  const rows = data.rows.map((row) =>
    data.columns.map((col) => String(row[col.key] ?? ""))
  );

  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: data.subtitle ? 38 : 32,
    theme: "grid",
    headStyles: {
      fillColor: [1, 66, 78],
      textColor: [255, 255, 255],
      fontSize: 9,
      fontStyle: "bold",
    },
    bodyStyles: {
      fontSize: 8,
      cellPadding: 3,
    },
    alternateRowStyles: {
      fillColor: [245, 247, 250],
    },
    margin: { left: 14, right: 14 },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Generated by EventHub on ${new Date().toLocaleDateString()} | Page ${i} of ${pageCount}`,
      14,
      doc.internal.pageSize.height - 10
    );
  }

  doc.save(`${data.title.replace(/\s+/g, "_").toLowerCase()}.pdf`);
}

/**
 * Export data to Excel
 */
export async function exportToExcel(data: ExportData): Promise<void> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "EventHub";
  workbook.created = new Date();

  const worksheet = workbook.addWorksheet(data.title.substring(0, 31));

  // Title row
  worksheet.mergeCells("A1:E1");
  const titleCell = worksheet.getCell("A1");
  titleCell.value = data.title;
  titleCell.font = { size: 16, bold: true, color: { argb: "FF01424E" } };
  titleCell.alignment = { horizontal: "left" };

  if (data.subtitle) {
    worksheet.mergeCells("A2:E2");
    const subtitleCell = worksheet.getCell("A2");
    subtitleCell.value = data.subtitle;
    subtitleCell.font = { size: 10, color: { argb: "FF64748B" } };
  }

  // Empty row
  const startRow = data.subtitle ? 4 : 3;

  // Headers
  const headerRow = worksheet.getRow(startRow);
  data.columns.forEach((col, index) => {
    const cell = headerRow.getCell(index + 1);
    cell.value = col.header;
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF01424E" },
    };
    cell.alignment = { horizontal: "center", vertical: "middle" };
    cell.border = {
      top: { style: "thin" },
      left: { style: "thin" },
      bottom: { style: "thin" },
      right: { style: "thin" },
    };
  });

  // Set column widths
  data.columns.forEach((col, index) => {
    const column = worksheet.getColumn(index + 1);
    column.width = col.width || 20;
  });

  // Data rows
  data.rows.forEach((row, rowIndex) => {
    const excelRow = worksheet.getRow(startRow + 1 + rowIndex);
    data.columns.forEach((col, colIndex) => {
      const cell = excelRow.getCell(colIndex + 1);
      cell.value = row[col.key] as string | number;
      cell.border = {
        top: { style: "thin" },
        left: { style: "thin" },
        bottom: { style: "thin" },
        right: { style: "thin" },
      };
      if (rowIndex % 2 === 1) {
        cell.fill = {
          type: "pattern",
          pattern: "solid",
          fgColor: { argb: "FFF1F5F9" },
        };
      }
    });
  });

  // Auto-filter
  worksheet.autoFilter = {
    from: { row: startRow, column: 1 },
    to: { row: startRow, column: data.columns.length },
  };

  // Generate and download
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${data.title.replace(/\s+/g, "_").toLowerCase()}.xlsx`;
  link.click();
  URL.revokeObjectURL(url);
}
